// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTk_jWqp4KhX5bbhUdT-RQvC73RsOI8og',
    appId: '1:384693868305:web:f8792d5d8953af30695eb0',
    messagingSenderId: '384693868305',
    projectId: 'wecheckappsa',
    authDomain: 'wecheckappsa.firebaseapp.com',
    storageBucket: 'wecheckappsa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU7V2EGCi-jGLLPnOtLs9EUQC6XVs1Jfs',
    appId: '1:384693868305:android:7a3fb39d6e0ab223695eb0',
    messagingSenderId: '384693868305',
    projectId: 'wecheckappsa',
    storageBucket: 'wecheckappsa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw7DE3vIpAzFebGpseKOBM4buqPJixylE',
    appId: '1:384693868305:ios:61fe60e0801e7ca5695eb0',
    messagingSenderId: '384693868305',
    projectId: 'wecheckappsa',
    storageBucket: 'wecheckappsa.appspot.com',
    iosClientId: '384693868305-48llt60r68gejdgo01odbbi0ndb4kj1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecheck',
  );
}
